### ISSUE TITLE
some problems about the project

### ISSUE THREAD

**Issue by 3015218116** [brandontrabucco/detailed_captioning#2]
I am sorry to bother you, but I have some questions about this project. I have read the paper of top-down and down-up attention, and I am very glad to find a version implemented by tensorflow. However, I have encountered problems according to the readme deployment project you provided. I hope to get your help
1. （Pycocoapi）, I visited the github, coke-caption you provided, but I found that there was no pycocoapi, so I directly extracted the file with the corresponding class, I don't know if it is correct to do so
2: （from object_detective.protos import graph_rewriter_pb2）, I downloaded the tensorflow model and placed object_detection into my project. Unfortunately, I could not find graph_rewriter_pb2, which is just one of them
I hope to get your reply. Thank you very much

**Comment by brandontrabucco** [comment]
Hello,

Thank you for your interest in my code. 

To your first question, I have pushed the version of the coco-caption repository that I am using to github. I have changed the name from 'pycocoapi' to 'coco_metrics', and it can be installed from [here](https://github.com/brandontrabucco/coco_metrics). 
In that version, I have migrated [Tsung-Yi Lin](https://github.com/tylin)'s implementation from python 2.7 to python 3.6, and have made it installable as a package.

To your second question, I cannot find references to 'from object_detection.protos import graph_rewriter_pb2' in this repository. If possible, could you clarify the details of this issue, and provide a reference from the source files?

Let me know if I can help clarify other parts of this project, Thanks!

Cheers,
Brandon

EDIT:

I have reproduced your second question. When installing the object_detection library, follow [these](https://github.com/tensorflow/models/blob/df122b1099dae807708e6baaf2c3d6398190ce7a/research/object_detection/g3doc/installation.md) instructions from the authors. In particular, make sure to compile the .proto files using protoc.

**Comment by 3015218116** [comment]
Thank you very much for your answer. All the problems have been solved. I am new to these things, so I am unfamiliar with them. As for the second question, I found it embarrassing that I didn't compile it. Thank you again.
